lenguaje: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "12"
git:
  depth: 3
script:
  - yarn test
notifications:
  email:
    recipients:
      - pjuanluis97@gmail.com
    on_success: always
    on_error: always
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key: 70767837-da16-4c64-abbb-e868aa1d2333
  app: pz-store-backend
  on:
    repo: pjuanluis/platzi-store-backend
